# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 13:52
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', imagekit.models.fields.ProcessedImageField(default='avatar/default.png', upload_to='avatar', verbose_name='头像')),
                ('sex', models.CharField(choices=[('M', 'man'), ('W', 'woman')], max_length=1)),
                ('address', models.CharField(max_length=250)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(code='invalid phone number', message='Phone number must be 11 digits.', regex='^\\d{11}$')])),
            ],
        ),
    ]
