# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='userid',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
